# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt


    - name: Run PyTest
      run: pytest --html=./pytest-report/report.html


    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
       name: test-results
       path: pytest-report/report.html
       if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to warn
